"""Create notification authority and outbox tables."""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "20260825_0001"
down_revision = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
def upgrade():
    op.create_table("notifications", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organization_id", sa.Uuid(), nullable=False), sa.Column("correlation_id", sa.Uuid(), nullable=False), sa.Column("kind", sa.String(32), nullable=False), sa.Column("monitor_id", sa.Uuid(), nullable=False), sa.Column("monitor_run_id", sa.Uuid(), nullable=False), sa.Column("diagnostic_job_id", sa.Uuid(), nullable=False), sa.Column("requested_by_user_id", sa.Uuid(), nullable=False), sa.Column("template_name", sa.String(64), nullable=False), sa.Column("template_data_json", postgresql.JSONB(), nullable=False), sa.Column("payload_fingerprint", sa.String(64), nullable=False), sa.Column("state", sa.String(24), nullable=False), sa.Column("lease_token_hash", sa.String(64)), sa.Column("lease_generation", sa.Integer(), nullable=False, server_default="0"), sa.Column("lease_expires_at", sa.DateTime(timezone=True)), sa.Column("email_delivery_id", sa.Uuid()), sa.Column("failure_code", sa.String(64)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("organization_id", "correlation_id", "kind", name="uq_notifications_organization_correlation_kind"), sa.CheckConstraint("state IN ('pending','claimed','email_attached','failed')", name="ck_notifications_state"), sa.CheckConstraint("kind = 'diagnostic_alert'", name="ck_notifications_kind"), sa.CheckConstraint("template_name = 'diagnostic_alert'", name="ck_notifications_template"))
    op.execute("ALTER TABLE notifications ADD CONSTRAINT ck_notifications_lease_generation CHECK (lease_generation >= 0)")
    op.execute("ALTER TABLE notifications ADD CONSTRAINT ck_notifications_failure_code CHECK (failure_code IS NULL OR failure_code IN ('recipient_unavailable','invalid_template','delivery_failed','member_removed'))")
    op.execute("ALTER TABLE notifications ADD CONSTRAINT ck_notifications_state_coherence CHECK ((state = 'claimed' AND lease_token_hash IS NOT NULL AND lease_expires_at IS NOT NULL AND email_delivery_id IS NULL AND failure_code IS NULL) OR (state = 'email_attached' AND lease_token_hash IS NULL AND lease_expires_at IS NULL AND email_delivery_id IS NOT NULL AND failure_code IS NULL) OR (state = 'failed' AND lease_token_hash IS NULL AND lease_expires_at IS NULL AND email_delivery_id IS NULL AND failure_code IS NOT NULL) OR (state = 'pending' AND lease_token_hash IS NULL AND lease_expires_at IS NULL AND email_delivery_id IS NULL AND failure_code IS NULL))")
    op.create_index("ix_notifications_claimable", "notifications", ["state", "lease_expires_at", "created_at"])
    op.create_table("outbox_events", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("aggregate_id", sa.Uuid(), nullable=False), sa.Column("payload_json", postgresql.JSONB(), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("next_attempt_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("event_type", "aggregate_id", name="uq_outbox_events_type_aggregate"), sa.CheckConstraint("attempt_count >= 0", name="ck_outbox_events_attempt_count"))
    op.create_index("ix_outbox_events_publication_eligibility", "outbox_events", ["published_at", "next_attempt_at", "created_at", "id"])
def downgrade():
    op.drop_table("outbox_events"); op.drop_table("notifications")
